name: Update Profile README

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

  workflow_dispatch:

  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install google-genai

      - name: Login GitHub CLI
        run: |
          gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate README with Gemini
        run: |
          python scripts/generate_readme.py
        env:
          API_KEY_AI: ${{ secrets.API_KEY_AI }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md

          if git diff --cached --quiet; then
            echo "Tidak ada perubahan."
            exit 0
          fi

          git commit -m "chore: update AI profile README"
          git push