name: Update Profile README

on:
  workflow_dispatch:

  schedule:
    - cron: "0 1 * * *"

  push:
    branches:
      - main
    paths:
      - "config/profile.yml"
      - "scripts/**"
      - ".github/workflows/update-profile-readme.yml"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate README
        env:
          API_KEY_AI: ${{ secrets.API_KEY_AI }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/generate_readme.py

      - name: Commit README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md

          if git diff --cached --quiet; then
            echo "README tidak berubah."
            exit 0
          fi

          git commit -m "chore: update profile README"
          git push
